version: "3.9"
services:
  nginx:
    build: .
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    ports:
      - "8080:8085"
      - "8081:8086"
    depends_on:
      - app
    environment:
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
    volumes:
      - /home/yillkid/.local/share/label-studio:/label-studio/data
      - ./deploy/nginx/certs:/certs:ro
    command: nginx

  app:
    stdin_open: true
    tty: true
    image: yillkid/jtbtech-label-studio:1.31.2
    container_name: labelstudio-app
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - JSON_LOG=1
    volumes:
      - /home/yillkid/.local/share/label-studio:/label-studio/data
    command: label-studio-uwsgi

